name: tidepool-data-science-simulator
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.12
  - black
  - coverage
  - flake8
  - matplotlib
  - mypy
  - numpy
  - pandas
  - pip
  - plotly
  - plotly-orca
  - pre-commit
  - pytest
  - python-dotenv
  - requests
  - scipy
  - seaborn
  - pip:
    - pip-chill==1.0.0
    - python-dotenv==0.13.0
    - git+https://github.com/tidepool-org/data-science-models@dev
    - git+https://github.com/tidepool-org/Pyloopkit@mjc/icgm_bolus_fix_positive_rc_momentum
    - git+https://github.com/tidepool-org/data-science-metrics
    - git+https://github.com/tidepool-org/LoopAlgorithmToPython
    # - -e file:/Users/mconn/tidepool/repositories/LoopAlgorithmToPython
